name: Deploy Subgraph to k8s

on:
  workflow_call:
    inputs:
      release_name:
        required: true
        type: string
      namespace: 
        required: true
        type: string
      values:
        required: true
        type: string
    secrets:
      github_token:
        required: true
      kubeconfig:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: 'Deploy'
        uses: 'glopezep/helm@v1.7.1'
        with:
          release: ${{ input.release_name }}
          namespace: ${{ input.namespace }}
          chart: './chart'
          token: '${{ secrets.github_token }}'
          helm: helm3
          values: ${{ input.values }}
        env:
          KUBECONFIG_FILE: '${{ secrets.kubeconfig }}'